### ISSUE TITLE
Fix race condition

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-floodsub#14]
https://travis-ci.org/libp2p/js-libp2p-floodsub/jobs/184988904#L1912

Ref #13

**Comment by diasdavid** [comment]
Are you on top of this one? Maybe @gavinmcdermott or @haadcode can give a hand? Thank you :)

**Comment by dignifiedquire** [comment]
I can dig into this once the release train is done. If someone else wants to start looking into this please do so :)

**Comment by gavinmcdermott** [comment]
@dignifiedquire / @diasdavid - The end of this week I need to finish porting Nomad over to the full JS implementation using pubsub for an upcoming multi-week build expedition with a handful of teams. I'd still love to help and if I can free up some time tomorrow or Friday, I'll let you know that I'm hopping in along with what I find.

**Comment by diasdavid** [comment]
Is this still a issue?

**Comment by diasdavid** [comment]
Seems it isn't :)
