### ISSUE TITLE
Pubsub has no peers in latest version

### ISSUE THREAD

**Issue by sethhrbek** [libp2p/js-libp2p-floodsub#168]
When creating a node with the following configuration:

```
    transports: [
      new TCP(),
      new WebSockets(),
      new WebRTCStar({wrtc}),
    ],
    connectionEncryption: [
      new Noise()
    ],
    streamMuxers: [
      new Mplex()
    ],
    pubsub: new FloodSub({
      enabled: true,
      canRelayMessage: true,
      emitSelf: false
    }),
    dht: new KadDHT({
      protocolPrefix: PROTOCOL_PREFIX,
      clientMode: false
    }),
    peerDiscovery: [
      webRtcStar.discovery
    ]
```

The newer versions of floodSub (>=2.0.0) don't work (messages don't get transferred between nodes). The farthest I've diagnosed this issue is the pubsub peer list is returning an empty array, despite the node having peers (`this.node.getPeers()` returns a populated array, `this.node.pubsub.peers` returns empty).

This issue does *not* exist when using floodsub < 2.0.0 (pubsub peer list is populated and pubsub messaging works).

Tested the issue on libp2p `0.37.2` and `0.37.3`

**Comment by BigLep** [comment]
@sethhrbek: this is surprising because we test message delivery in our test suite.  Can you please put together a reproduction case that maintainers can easily run?

Also, is there any reason you're not using gossipsub?
