### ISSUE TITLE
Messages are being written out of order

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-floodsub#18]
Although there is no promise that in a FloodSub network messages are delivered sequencially (due to retransmissions, forwarding etc), it should be impossible for 2 nodes connected over TCP, one publisher and one subscriber, to see the messages from the other arrived unordered. 

See more here: https://github.com/ipfs/js-ipfs/pull/644#issuecomment-272175161

**Comment by diasdavid** [comment]
This is mainly cause because the publish callback is called right away, even before the write, which in a case of thousands of messages being written, floods the timecache and forces it to start discarding.

**Comment by dignifiedquire** [comment]
Which callback are you referring to? `publish` is sync on `master`.

**Comment by diasdavid** [comment]
Something is wrong, I thought initially that the API was 'false sync', but it actually might be a time-cache problem, @dignifiedquire do you have time to look into this https://github.com/libp2p/js-libp2p-floodsub/pull/19 today?

**Comment by dignifiedquire** [comment]
@diasdavid I am very confused right now, I cloned things and installed and linked but I can not reproduce the issue, after running the latest pubsub tests in js-ipfs about 10 times.

The only fixes I needed to pull in were: https://github.com/libp2p/js-libp2p-crypto/pull/56 Could you please check if this works for you as well with that fix? 

My suspicion is that the random value generation is broken in node4, resulting in incorrect id generation, resulting in the issue you were seeing.

**Comment by diasdavid** [comment]
Will test asap :)

**Comment by diasdavid** [comment]
Everything is fine now :D
