### ISSUE TITLE
Wonderful spec

### ISSUE THREAD

**Issue by gavinmcdermott** [libp2p/js-libp2p-floodsub#3]
<img width="439" alt="screen shot 2016-09-28 at 11 12 46 pm" src="https://cloud.githubusercontent.com/assets/302978/18942906/16a81d62-85d1-11e6-9541-5128b6670e48.png">

This might be the best spec visual I've ever seen. Wonderful descriptions. Did you use a tool to generate these? Curious, as it seems crazy useful when talking about topologies...

**Comment by diasdavid** [comment]
:D thank you @gavinmcdermott! 

I used [monodraw](https://monodraw.helftone.com/), it is the best ascii drawing tool I've ever used :)

**Comment by kumavis** [comment]
That is a fine tool indeed!

also this issue can be closed @gavinmcdermott
