### ISSUE TITLE
Generic pubsub debug naming guideline

### ISSUE THREAD

**Issue by gavinmcdermott** [libp2p/js-libp2p-floodsub#5]
If we end up adding in the log statements mentioned in [this issue](https://github.com/libp2p/js-libp2p-floodsub/issues/4) and removing an extra logging library, then, so that others can use the visualization tool by dumping their own logs, maybe we have a naming convention that folks use when testing.

Something that includes:
- **Debug naming guideline**: Example: `strategy:<some_name>` so that the log parser can find logs
- **Debug event log data format**: 
  - `floodsub` uses: `<timestamp> <event_type> <time_to_log> <topics> <msg>`
  - `pstn-logger` uses: `<timestamp> <event_type> <source_b58id> <b64_topics> <b64_msgs>`

For example, here's what I have going on in the `logger` for publish and receive...

```
Tue, 04 Oct 2016 03:46:56 GMT pstn:logger <event_type> <b58_event_src_node_id> <b64_topics> <b64_msgs>
```

Currently I'm having the stats consume something like the above ([example tests](https://github.com/gavinmcdermott/js-libp2p-pstn-stats/blob/master/test/statistics.spec.js#L17-L19)), but if we want to standardize something else, now is a good time to decide. 

It'd be great to standardize so that others can simply format their logs accordingly and then use the emerging visualization/benchmark tools.

**Comment by diasdavid** [comment]
What about wrapping `debug` in a function that checks for a `LOG` env variable that can take two options: a) short, b) long, where a) is a human readable (only minimum necessary information) and b) is a version with everything a tool like pstn might need. It should default to a), but can be enabled with `LOG=long` at any time.

If the above sounds good, feel free to PR this and add all the information you might need or dream of to the `long` version :)

**Comment by gavinmcdermott** [comment]
I like this...I'll add it to my list :)

**Comment by diasdavid** [comment]
@gavinmcdermott let's keep the issue open until there is a PR with the changes, so we don't forget about it  :)
