### ISSUE TITLE
floodsub may dial the same peer twice concurrently

### ISSUE THREAD

**Issue by dirkmc** [libp2p/js-libp2p-floodsub#62]
Floodsub dials peers
- on startup (all the peers in its peer book)
- whenever it receives a `peer:connect` event

A `peer:connect` event can fire repeatedly for the same peer, eg if the underlying transport is connected to a rendezvous server, it will receive `peer:connect` every 10 seconds. In this case floodsub may dial the same peer concurrently. On connect this causes strange things to happen, eg [sending subscriptions twice](https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/index.js#L50) and [calling Peer.attachConnection()](https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/peer.js#L81) twice, which will cause a connection to leak

Happy to submit a PR to fix this. What would be the best approach?

<img width="1280" alt="screen shot 2018-11-27 at 6 10 57 pm" src="https://user-images.githubusercontent.com/169124/49118113-3210fb00-f271-11e8-8941-549a59291e04.png">

**Comment by vasco-santos** [comment]
Thanks for reporting this issue @dirkmc 

This is really annoying and should be fixed! Having a quick analysis over the codebase, I think we should be able to fix this using a logic similar to what is being done in [libp2p/js-libp2p-floodsub/src/base.js#L48-L56](https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/base.js#L48-L56). So, when we receive the `peer:connect` event, we should verify if we have that peer already. If we do not have it, we dial it. 

What do you think? I would appreciate if you could do the PR 😀

**Comment by dirkmc** [comment]
@vasco-santos I think we're [already checking](https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/base.js#L85) if we have the peer before dialing. The problem is that dialing can take some time, and the peer doesn't get added until after the dial is complete.

I think we may instead need to keep a `Map { peerId => boolean <isDialing> }`. This will also help us handle the case where a dial completes after the peer has been stopped (in which case we should close the connection)

I think it may help with testing to add a couple of events when a dial starts and completes, and maybe for start / stop. Are you ok with me adding these events with a similar signature to `floodsub:subscription-change`, eg `floodsub:dial`?

**Comment by vasco-santos** [comment]
Thanks for the deep analysis @dirkmc . I will look into you PR
